#!/bin/sh -e
unset $(env | grep ^npm | cut -d= -f1)
DIR="$(cd "$(dirname "$0")" && pwd)"
TMP=$(mktemp -d /tmp/shrinkwrap-XXXXXX)
trap "rm -r \"$TMP\"" 0
cd "$TMP"
ln -s "$OLDPWD/package.json"
ln -s "$OLDPWD/node_modules"
ln -s "$DIR/shrinkwrap.js"
NODE_PATH=/usr/local/lib/node_modules ./shrinkwrap.js "$@"
cp npm-shrinkwrap.json "$OLDPWD"
