#!/bin/bash
remote=$(jq -r .env.default.db < .couchapprc)
if diff -u \
  <(curl -s $remote/_design/publish |jq 'del(._id) | del(._rev) | del(.rev)') \
  <(couchapp push --export | jq 'del(._id) | del(._rev) | del(._attachments)') \
    | grep -c ^ >/dev/null ; then
  echo "Updating design document."
  couchapp push --docid _design/publish
else
 echo "Not changed"
fi
